spring.application.name=product-management-system

server.port=8080

spring.security.user.name=Admin
spring.security.user.password=Admin123

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
